# --- !Ups
create schema if not exists PUBLIC_BUBBLE;

CREATE TABLE PUBLIC_BUBBLE.BLOG
(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT,
    AUTHOR TEXT,
    INTRO TEXT,
    CONTENT TEXT,
    PUBLISH_DATE DATE,
    IMAGE_1_URL TEXT
);
Commit;

create table PUBLIC_BUBBLE.EVENT (
   ID SERIAL PRIMARY KEY,
   TITLE TEXT,
   LOCATION TEXT,
   START_TIME TIMESTAMP,
   END_TIME TIMESTAMP,
   DESCRIPTION TEXT,
   IMAGE_1_URL TEXT
);
Commit;


create table PUBLIC_BUBBLE.USER (
   ID SERIAL PRIMARY KEY,
   EMAIL TEXT,
   ROLE TEXT
);

# --- !Downs
drop table PUBLIC_BUBBLE.BLOG;
drop table PUBLIC_BUBBLE.EVENT;
drop table PUBLIC_BUBBLE.USER;