# --- !Ups
CREATE TABLE PUBLIC_BUBBLE.STATIC_CONTENT
(
    ID INTEGER PRIMARY KEY,
    CONTENT TEXT,
    IMAGE_URL TEXT
);
Commit;

INSERT INTO PUBLIC_BUBBLE.STATIC_CONTENT values (1, 'text', 'image')

# --- !Downs
drop table PUBLIC_BUBBLE.STATIC_CONTENT;
