# --- !Ups

CREATE TABLE PUBLIC_BUBBLE.BLOG
(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT,
    AUTHOR TEXT,
    INTRO TEXT,
    CONTENT TEXT,
    PUBLISH_DATE DATE,
    IMAGE_1_URL TEXT
);

create table PUBLIC_BUBBLE.EVENT (
   ID SERIAL PRIMARY KEY,
   TITLE TEXT,
   LOCATION TEXT,
   DESCRIPTION TEXT,
   DISPLAY_FROM DATE,
   DISPLAY_UNTIL DATE,
   IMAGE_1_URL TEXT
);

create table PUBLIC_BUBBLE.USER (
   ID SERIAL PRIMARY KEY,
   EMAIL TEXT,
   ROLE TEXT
);

# --- !Downs
drop table PUBLIC_BUBBLE.BLOG;
drop table PUBLIC_BUBBLE.EVENT;
drop table PUBLIC_BUBBLE.USER;