# --- !Ups

CREATE TABLE BLOG
(
ID INTEGER PRIMARY KEY,
TITLE varchar(255) NOT NULL,
AUTHOR varchar(255),
CONTENT varchar(255)
);

create table EVENT (
   ID SERIAL PRIMARY KEY,
   TITLE VARCHAR(50),
   LOCATION VARCHAR(80),
   DESCRIPTION VARCHAR(1000),
   DISPLAY_FROM DATE,
   DISPLAY_UNTIL DATE,
   IMAGE_1 VARCHAR
);

create table PUBLIC_BUBBLE_USER (
   ID SERIAL PRIMARY KEY,
   EMAIL VARCHAR(100),
   ROLE VARCHAR(100)
);

# --- !Downs
drop table BLOG;
drop table EVENT;
drop table PUBLIC_BUBBLE_USER;
