# --- !Ups

CREATE TABLE PUBLIC_BUBBLE.BLOG
(
    ID SERIAL PRIMARY KEY,
    TITLE varchar(255) NOT NULL,
    AUTHOR varchar(255),
    INTRO varchar(400),
    CONTENT varchar(4000),
    DISPLAY_FROM DATE,
    DISPLAY_UNTIL DATE,
    IMAGE_1_URL VARCHAR
);

create table PUBLIC_BUBBLE.EVENT (
   ID SERIAL PRIMARY KEY,
   TITLE VARCHAR(50),
   LOCATION VARCHAR(80),
   DESCRIPTION VARCHAR(1500),
   DISPLAY_FROM DATE,
   DISPLAY_UNTIL DATE,
   IMAGE_1_URL VARCHAR
);

create table PUBLIC_BUBBLE.USER (
   ID SERIAL PRIMARY KEY,
   EMAIL VARCHAR(100),
   ROLE VARCHAR(100)
);

# --- !Downs
drop table PUBLIC_BUBBLE.BLOG;
drop table PUBLIC_BUBBLE.EVENT;
drop table PUBLIC_BUBBLE.USER;